name: NowNest
options:
  bundleIdPrefix: com.foculoom
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "3"
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    DEVELOPMENT_TEAM: "H8MJMBTFVP"
    CODE_SIGN_STYLE: Automatic
targets:
  NowNest:
    type: application
    platform: iOS
    sources:
      - NowNest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.nownest
        INFOPLIST_FILE: NowNest/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
    dependencies: []
  NowNestTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - NowNestTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.nownest.tests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: NowNest
  NowNestUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - NowNestUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.nownest.uitests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: NowNest